// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoomManager.Infrastructure.Data;

#nullable disable

namespace RoomManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RoomManagerDbContext))]
    [Migration("20240613181254_AddDictRoomServiceConfiguration")]
    partial class AddDictRoomServiceConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoomManager.Domain.Entities.Dicts.DictRoomService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Название удобства");

                    b.Property<int?>("SerialNumber")
                        .HasColumnType("integer")
                        .HasComment("Порядковый номер для отображения");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("dict_room_service", "dict", t =>
                        {
                            t.HasComment("Справочник удобств в номере");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
